name: Linux build
on:
   push:
     branches: [ "master", "develop" ]
   pull_request:
     branches: [ "develop" ]
permissions:
   contents: read
   actions: read
   packages: read
   
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: '${{ matrix.os }}, build:${{ matrix.build_type }}, static:${{ matrix.static }}, ccov:${{ matrix.code_coverage }}'
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-24.04, ubuntu-22.04, ubuntu-26.04]
        build_type: [Debug,Release]
        cpp_compiler: [g++]
        static: ["false"] #Linux libraries (Boost, OpenSSL) are linked to the dynamic version of libstdc++
        include:
        - os: ubuntu-26-04
          build_type: Release
          cpp_compiler: clang++
          static: "false"
    steps:
    - uses: actions/checkout@v6
    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - name: Dependencies
      run: >
          sudo apt-get update && sudo apt-get -y install cmake valgrind libssl-dev zlib1g-dev libboost-test-dev libboost-filesystem-dev 
          libboost-iostreams-dev libboost-program-options-dev libboost-system-dev libboost-thread-dev libboost-date-time-dev
      # Install extra deps for ubuntu 26-04 (and add valgrind and coverage tests)
    - name: Extra Dependecies Ubuntu 26.04
      if: ${{ matrix.os == 'ubuntu-26.04' }}
      run: >
        sudo apt-get install -y libjitterentropy3-dev valgrind lcov gcovr
    #- name: Install cmake 4
    #  run: |
    #       test -f /usr/share/doc/kitware-archive-keyring/copyright || wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | \
    #          gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
    #       source /etc/os-release && echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ ${UBUNTU_CODENAME} main" | \
    #          sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null 
    #       sudo apt-get update
    #       sudo apt-get install -y cmake cmake-data
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: >
        /usr/bin/cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}
        -DSTATIC_RUNTIME:BOOL=${{matrix.static}}
        -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install
        -DLCC_PROJECT_NAME=MYPROJECT
    - name: Build
      # Build your program with the given configuration. 
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
           /usr/bin/cmake --build ${{ steps.strings.outputs.build-output-dir }} -j $(nproc) --target install --config ${{ matrix.build_type }}
    - name: Inspect
      run: |
        ls -la /proc; 
        ls -la /proc/hypervisor; ls -la /proc/device-tree;
        cat /proc/cmdline;
        cat /proc/cpuinfo; 
    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest . --build-config ${{ matrix.build_type }} --output-on-failure
      env:
         CTEST_OUTPUT_ON_FAILURE: 1
         BOOST_TEST_LOG_LEVEL: message
         VIRTUAL_ENV: VM

